[project]
name = "raptor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.4.9",
    "numpy>=2.3.4",
    "openai>=2.6.0",
    "scikit-learn>=1.7.2",
    "tiktoken>=0.12.0",
    "umap>=0.1.1",
]
